### PR TITLE
Updated node dependencies to fix trivy lint errors

### PR DESCRIPTION
**Pull request by meenubhooshanan**
Attempted to fix the package-lock.json library version issues highlighted from #41. Please test!

### CODE REVIEW

**Review by wesley-dean-gsa — COMMENTED** [review]
@meenubhooshanan quick question..  I see that the `pacakge-lock.json` file was update (cool, thank you!) but Git's saying the `package.json` hasn't been updated in 2 months.

https://github.com/IMLS/estimating-wifi/blob/41-trivy/imls-directus/package.json

I'm not a Node developer, but I have noticed that often the `package.json` file will be updated by a developer, then the `package-lock.json` file is updated via `npm` (e.g., `npm install --package-lock-only`), and finally both files are added, committed, and pushed.

Can you share any thoughts?  It's entirely possible that what I've written is a result of my own ignorance in which case I would appreciate the opportunity to learn more.

**Comment by meenubhooshanan** [comment]
@wesley-dean-gsa Thanks for bringing this up. I just ran `npm update` and `npm audit fix` to fix the flagged issues, which is why only package-lock.json was updated. I only updated existing packages, none were added.

I noticed that the `package.json` didn't contain the several hundreds of packages represented in the `package-lock.json` file, so I assumed that I didn't need to add the updated versions of the packages flagged as issues in `package-lock.json` to `package.json`

I'm assuming that the [package-lock.json dependencies are sub-dependencies](https://dillionmegida.com/p/package-vs-package-lock-json/) from the dependencies in `package.json` (which is why it's longer), but I'm not sure. @jadudm @cantsin any thoughts?

**Comment by wesley-dean-gsa** [comment]
Ahhh!  Awesome!!

Yes, I believe you are correct.  Thanks!

Also, approved!!!

**Review by wesley-dean-gsa — APPROVED** [review]
Excellent.  Thank you.

**Pull request merged**
