### PR TITLE
Precommit

### PR DESCRIPTION
**Pull request by wesley-dean-gsa**
This adds a very basic pre-commit configuration to make sure we don't push API keys, tokens, credentials, etc..

### CODE REVIEW

**Comment by wesley-dean-gsa** [comment]
[pre-commit](https://pre-commit.com/) is a developer-side tool that runs tests on source code prior to a commit being created (and pushed).  The configuration file included here only has very basic checks (e.g., no merge conflicts, no trailing whitespaces, etc.) and scans for credentials (API keys, tokens, etc.).

Installing a pre-commit hook is something developers opt-in to using.  After pre-commit is installed on the system (potentially via pip as it's a Python program), one may configure their local repository by running `pre-commit install` from the repository.  If one opts not to setup a pre-commit hook on their system, everything will continue to function as usual.  It's also possible to run `git commit` without checks on a one-off basis.

**Review by sknep — APPROVED** [review]
seems cool :)

**Comment by sknep** [comment]
Would you be interested in adding docs to the readme so that future contributors will know this is available to them?

**Comment by wesley-dean-gsa** [comment]
@sknep yes, excellent point!  I'll update the documentation and then resubmit the PR.

Thanks!

**Comment by wesley-dean-gsa** [comment]
@sknep I added a document to doc/ with development notes; currently, it just has the pre-commit stuff but my hope is to expand it as work continues

**Pull request merged**
