### PR TITLE
updated functions to add fscs_id as a return field

### PR DESCRIPTION
**Pull request by anagradova**
lib_search_name and lib_search_state were updated to append the fscs_id to the returned record

### CODE REVIEW

**Review by bklaas — COMMENTED** [review]
I'm fine with the change. One Q: is there a unit test for this function, and does it need modification in order to pass with the new CONCAT() bits?

**Comment by sknep** [comment]
Let me know when this is approved & merged so I can pull the changes into my latest. I think this will allow me to remove some front end code, which is always nice :)

**Comment by anagradova** [comment]
Added tests for the search functions in test_public_queries and used the fscs_id as the asserted values.

**Comment by sknep** [comment]
FYI reviewers (@meenubhooshanan and @bklaas) the PR is going to need an official "approve" before the branch protections will allow a merge -- a comment isn't going to qualify anymore :)

**Review by bklaas — APPROVED** [review]
Thanks for adding the unit test, looks great!

**Pull request merged**
