### PR TITLE
Un-fakified the preload data.

### PR DESCRIPTION
**Pull request by jadudm**
This changes the libraries from made-up FCFS ids (AA000x-001) to *real* library ids.

The library IDs chosen are for real libraries, but the data in the file does *not* correspond to the libraries indicated. We have done this so that we can test interface elements that require lookups using real FCFS library ids.

### CODE REVIEW

**Comment by sknep** [comment]
@jadudm What is the list of "good" ids that we can now query against?

**Comment by jadudm** [comment]
That commit adds a section to the README that documents the library ids in the fakified/unfakified dataset.

**Comment by anagradova** [comment]
I looked through the gz file and it appears to good.

**Comment by sknep** [comment]
do we need to rectify these merge conflicts @jadudm ?

**Comment by sknep** [comment]
@jadudm this is so close to the finish line! Would you have a moment to resolve the conflicts?

**Pull request closed without merging**
